name: quic
version: '0.1.0.0'
description: quic implementation
category: Web
author: Koichi Nakanishi
maintainer: keizo042dev@gmail.com
copyright: 2017 Koichi Nakanishi
license: BSD3
github: keizo042/quic
extra-source-files:
- README.md
dependencies:
- base
library:
  exposed-modules:
  - Network.QUIC
  - Network.QUIC.Types
  dependencies:
  - bytestring
  - cryptonite
  - async
  - network
  - time
  - binary
  - containers
  - tls
  - array
  - data-default-class
tests:
  quic-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit
    - quic
